######################################################################
# Automatically generated by qmake (3.0) Sat Dec 31 18:42:03 2016
######################################################################

TEMPLATE = app
TARGET = MatchThree
INCLUDEPATH += .

# Input
SOURCES += MatchThree.cpp
QT += widgets
